version: '2'

networks:
  rc_net:
    driver_opts:
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0
      com.docker.network.driver.mtu: 1500
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:

  nginx:
    image: nginx:latest
    container_name: www-nginx
    hostname: www-nginx
    depends_on:
      - php
      - mysql
    restart: always
    networks:
      rc_net:
        ipv4_address: 172.20.0.5
    volumes:
      - ./www/wwwroot:/www:rw
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime
    ports:
      - "9001:80"

  php:
    build:
      context: ./php/.
    container_name: www-php
    hostname: www-php
    volumes:
      - ./www/wwwroot:/www:rw
    ports:
      - "9000:9000"
    networks:
      rc_net:
        ipv4_address: 172.20.0.7
    depends_on:
      - mysql

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: www-phpmyadmin
    hostname: www-phpmyadmin
    ports:
      - "9002:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${MYSQL_HOST}
    restart: always
    networks:
      rc_net:
        ipv4_address: 172.20.0.10
    depends_on:
      - mysql
  mysql:
    image: mysql:${MYSQL_VERSION}
    #container_name: ${MYSQL_HOST}
    container_name: www-mysql
    hostname: www-mysql
    restart: always
    env_file:
      - ".env"
    networks:
      rc_net:
        ipv4_address: 172.20.0.6
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "9003:3306"
    restart: always
#    volumes:
      - ./database:/var/lib/mysql:rw
      #- ./sock:/var/run/mysqld:rw
      - /etc/localtime:/etc/localtime
